# Generated by Django 4.0.1 on 2022-01-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_date_meet_enddate_meet_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='startDate',
        ),
    ]
