# Generated by Django 4.0.1 on 2022-01-12 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_date_remove_meet_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='meet',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='meet',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
