# Generated by Django 4.0.1 on 2022-01-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_date_meet_enddate_meet_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meet',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
