# Generated by Django 4.0.1 on 2022-01-12 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_meet_enddate_alter_meet_startdate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
