# Generated by Django 4.0.1 on 2022-01-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_event_entriespath_remove_meet_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meetid',
            field=models.IntegerField(default=0),
        ),
    ]
