# Generated by Django 4.0.1 on 2022-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_meet_meetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='meetid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
