# Generated by Django 4.0.1 on 2022-01-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fantasyentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FantasyEntry',
        ),
    ]
