# Generated by Django 4.0.1 on 2022-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fantasyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('height', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('dd', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dives',
        ),
        migrations.DeleteModel(
            name='FantasyEntry',
        ),
        migrations.AddField(
            model_name='entry',
            name='dives',
            field=models.ManyToManyField(to='core.Dive'),
        ),
    ]
