# Generated by Django 4.0.1 on 2022-01-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dive_remove_entry_dives_delete_fantasyentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='number',
            field=models.CharField(max_length=6),
        ),
    ]
