# Generated by Django 4.0.1 on 2022-01-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_dive_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='dives',
        ),
        migrations.CreateModel(
            name='DiveInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dive')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entry')),
            ],
        ),
    ]
