# Generated by Django 4.0.1 on 2022-01-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fantasyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyentry',
            name='dive1',
        ),
    ]
