# Generated by Django 4.0.1 on 2022-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_fantasyentry_dive1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyentry',
            name='dives',
            field=models.ManyToManyField(to='core.DiveInstance'),
        ),
    ]
