# Generated by Django 4.0.1 on 2022-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_fantasyentry_dives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyentry',
            name='dives',
            field=models.ManyToManyField(to='core.DiveInstance'),
        ),
    ]
