# Generated by Django 4.0.1 on 2022-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_diveinstance_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveinstance',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
