# Generated by Django 4.0.1 on 2022-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_diveinstance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='hasResults',
        ),
        migrations.AddField(
            model_name='event',
            name='hasResults',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diveinstance',
            name='score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='entriesPath',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
