# Generated by Django 4.0.1 on 2022-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_meet_hasresults_event_hasresults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveinstance',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
