# Generated by Django 4.0.1 on 2022-01-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_diveinstance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyentry',
            name='totalScore',
            field=models.FloatField(default=0),
        ),
    ]
