# Generated by Django 4.0.1 on 2022-01-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fantasyentry_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='totalScore',
            field=models.FloatField(default=0),
        ),
    ]
