# Generated by Django 4.0.1 on 2022-01-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_entry_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyentry',
            name='name',
            field=models.CharField(default='Luke Foster', max_length=50),
            preserve_default=False,
        ),
    ]
